model:
  sequence_length: 12
  prediction_horizon_60: 12
  prediction_horizon_120: 24
  batch_size: 32
  epochs: 100
  learning_rate: 0.001
  dropout_rate: 0.3
  l2_regularization: 0.001

data:
  features:
    - insulin
    - calories
    - steps
    - carb_input
    - glucose
  test_size: 0.2
  random_state: 42

paths:
  data_dir: "./data"
  models_dir: "./models"
  results_dir: "./results"