model:
  sequence_length: 12
  prediction_horizon_60: 12
  prediction_horizon_120: 24
  lstm_units_60: 64
  lstm_units_120: 64
  cnn_filters: 64
  dropout_rate: 0.3
  l2_reg: 0.001
  batch_size: 32
  epochs: 100
  learning_rate: 0.001
  patience: 10

data:
  features:
    - insulin
    - calories
    - steps
    - carb_input
    - glucose
  test_size: 0.2
  random_state: 42
  validation_split: 0.2

evaluation:
  save_plots: true
  plot_format: 'png'
  plot_dpi: 300
  clarke_analysis: true
  generate_reports: true

paths:
  data_dir: "./data"
  models_dir: "./models"
  results_dir: "./results"
  plots_dir: "./plots"
  logs_dir: "./logs"